[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/donate/*"
  to = "/donate"
  status = 200
  force = true

[[redirects]]
  from = "/project/*"
  to = "/project"
  status = 200
  force = true

