[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/donate/:id"
  to = "/donate"
  status = 200
  force = true

[[redirects]]
  from = "/project/:id"
  to = "/project"
  status = 200
  force = true

[[redirects]]
  from = "/user/:address"
  to = "/user"
  status = 200
  force = true

[context.develop]
  SEGMENT_PRODUCTION_WRITE_KEY = "MHK95b7o6FRNHt0ZZJU9bNGUT5MNCEyB"

[context.staging]
  SEGMENT_PRODUCTION_WRITE_KEY = "MHK95b7o6FRNHt0ZZJU9bNGUT5MNCEyB"