[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/donate/:id"
  to = "/donate"
  status = 200
  force = true

[[redirects]]
  from = "/donate"
  to = "/donate/:id"
  status = 200
  force = true
  query = {id = "giveth"}

[[redirects]]
  from = "/project/:id"
  to = "/project"
  status = 200
  force = true

[[redirects]]
  from = "/user/:address"
  to = "/user"
  status = 200
  force = true
